### PR TITLE
Read WindowCoveringConfig and set correct names

### PR DESCRIPTION
**Pull request by granturism0**
- Implementation of WindowCoveringConfig
- Setting the names for blinds using the WebGUI
- Improvement detection of IP changes

### CODE REVIEW

**Comment by johannrichard** [comment]
@granturism0 thanks again for the contributions, will have a more thorough look at them. 

After a quick glance, let me offer a few observations: 

- I see you're running into quite a few code style issues when submitting PR's, may I ask if you have some tasks that run prettier before saving in your IDE -- could save you some hassles (I use [VSCodium](https://vscodium.com) which has all the bells and whistles integrated / loaded with extensions, but I also understand if you prefer something else)
- I'm currently working on a quite comprehensive overhaul (as per #103) and have just pushed the branch for the first time: [v2.0.0-refactor](johannrichard/homebridge-dingz/tree/v2.0.0-refactor) -- before you continue to work on the `master`/ old code, you might want to have a look at it

**Comment by johannrichard** [comment]
PS: You might also want to check-out the `v2.0.0-nightly.x` for some (early) testing: I'm publishing these to npm quite regularly under `homebridge-dingz@nightly` with the latest features in that branch.

**Comment by granturism0** [comment]
> @granturism0 thanks again for the contributions, will have a more thorough look at them.
> 
> After a quick glance, let me offer a few observations:
> 
> * I see you're running into quite a few code style issues when submitting PR's, may I ask if you have some tasks that run prettier before saving in your IDE -- could save you some hassles (I use [VSCodium](https://vscodium.com) which has all the bells and whistles integrated / loaded with extensions, but I also understand if you prefer something else)
> * I'm currently working on a quite comprehensive overhaul (as per #103, #116, #120, and #123) and have just pushed the branch for the first time: [v2.0.0-refactor](johannrichard/homebridge-dingz/tree/v2.0.0-refactor) -- before you continue to work on the `master`/ old code, you might want to have a look at it

Sorry, about the style errors. I will correct them in some minutes

**Comment by johannrichard** [comment]
PPS: No problem, my setup *is* quite strict in terms of code formatting. 

Just a hint: you don't have to close the PR's for new commits. New commits from the same branch you develop in will be added to the PR as long as the PR is open, so you can just continue to work on the code and commit without opening a new PR. This is quite handy if code-reviews / changes are requested before merging.

**Pull request closed without merging**
