### PR TITLE
Read WindowCoveringConfig and set correct names

### PR DESCRIPTION
**Pull request by granturism0**
- Implementation of WindowCoveringConfig
- Setting the names for blinds using the WebGUI
- Improvement detection of IP changes

### CODE REVIEW

**Comment by granturism0** [comment]
Hello @johannrichard 
So, sorry for the necessary style corrections, but now everything should be checked in correctly.
I have made several changes in the code so that the names of the engines are now also loaded cleanly from the web config.
Hope this fits for you :-)
Best regards
@granturism0

**Comment by granturism0** [comment]
Hello @johannrichard 
Yes, I notice that you are currently working on various adaptations for V2.0. If necessary, you can include my revisions in this comprehensive revision. I would be happy if this still fits.
You can send me the link to this nightly build. Then I can test the complete revisions including my adjustments again.
Best regards
@granturism0

**Comment by johannrichard** [comment]
> So, sorry for the necessary style corrections, but now everything should be checked in correctly.

No worries, we're all learning and my code is far froM perfect.

> I have made several changes in the code so that the names of the engines are now also loaded cleanly from the web config.

Great, makes sense and I'll have a look at it. Might integrate it slightly different into the `v2.0.0-refactor` branch as I have started to cleanup quite a bit the mess my code is. 😁😅 

> Hope this fits for you :-)

All contributions are welcome. 😃 :octocat:

**Comment by granturism0** [comment]
PS: I have now also installed VSCodium.
I usually work with VS Studio on the Mac.

**Comment by johannrichard** [comment]
> PS: I have now also installed VSCodium.
> I usually work with VS Studio on the Mac.

Apologies if I run into open doors re:style & formatting: I vaguely remember that I had to install the `esbenp.prettier-vscode` extension to use Prettier specifically in Visual Studio Code/VSCodium to have consistent formatting. 

```
ext install esbenp.prettier-vscode
```

**Comment by johannrichard** [comment]
> Apologies if I run into open doors re:style & formatting: I vaguely remember that I had to install the `esbenp.prettier-vscode` extension to use Prettier specifically in Visual Studio Code/VSCodium to have consistent formatting.

As a matter of fact, I have just realised that my `vscode` settings *in the project* were somehow incomplete, too. If you pull the latest changes from the [master](/johannrichard/homebridge-dingz/tree/master) branch, you'll get an updated `.vscode/settings.json` file in the project which picks up prettier as default (according to [this guide](https://glebbahmutov.com/blog/configure-prettier-in-vscode/#vscode-setup)). I wonder why I haven't seen that earlier. 🤦

**Comment by granturism0** [comment]
> > PS: I have now also installed VSCodium.
> > I usually work with VS Studio on the Mac.
> 
> Apologies if I run into open doors re:style & formatting: I vaguely remember that I had to install the `esbenp.prettier-vscode` extension to use Prettier specifically in Visual Studio Code/VSCodium to have consistent formatting.
> 
> ```
> ext install esbenp.prettier-vscode
> ```

Thanks for your comments.
I have now made a few optimizations for me, so that I can at least see the styling errors in build.
But the plugin makes even more sense if you have the rules anyway.

**Pull request closed without merging**
